### ISSUE TITLE
Change sitemap-index to sitemap

### ISSUE THREAD

**Issue by ErikThiart** [frostschutz/MyBB-Google-SEO#55]
Hello,

Is there a specific reason why you named it sitemap-index concidering google, bing etc crawl and search for a file sitemap.xml by default.

Is there a way I can change that filename from sitemap-index to just sitemap without breaking your plug in?

Apart from that, stunning flippen plugin man keep it up!!

**Comment by ErikThiart** [comment]
I assume I can override it with the robots.txt?

**Comment by frostschutz** [comment]
There might already be a /sitemap.xml (you can have multiple sitemaps) and MyBB might just be in a subdir. You should just specify the sitemap(s) in robots.txt, that's what all search engines understand. With Google you can also add it in the webmaster tools.

**Comment by ErikThiart** [comment]
Yea I figured, I changed it in the robots now all is good! Sorry about this, it was a noob moment on my part :P
